<?php

namespace Database\Seeders;

use App\Models\Achievement;
use Illuminate\Database\Seeder;

class AchievementsSeeder extends Seeder
{
    public function run(): void
    {
        // Phase 1 achievements only — auto-awarded by the service
        $achievements = [
            [
                'name'           => ['en' => 'First Drop of Life',  'ar' => 'قطرة الحياة الأولى'],
                'description'    => ['en' => 'Complete your first blood donation.', 'ar' => 'أتممت أول تبرع بالدم.'],
                'criteria_type'  => 'donations',
                'criteria_value' => 1,
                'points_rewards' => 50,
                'badge_type'     => 'bronze',
                'badge_icon'     => 'achievements/first-drop.png',
                'display_order'  => 1,
            ],
            [
                'name'           => ['en' => 'The Contributor',     'ar' => 'المساهم'],
                'description'    => ['en' => 'Donate blood 3 times.', 'ar' => 'تبرعت بالدم 3 مرات.'],
                'criteria_type'  => 'donations',
                'criteria_value' => 3,
                'points_rewards' => 75,
                'badge_type'     => 'bronze',
                'badge_icon'     => 'achievements/contributor.png',
                'display_order'  => 2,
            ],
            [
                'name'           => ['en' => 'The Savior',          'ar' => 'المنقذ'],
                'description'    => ['en' => 'Donate blood 5 times.', 'ar' => 'تبرعت بالدم 5 مرات.'],
                'criteria_type'  => 'donations',
                'criteria_value' => 5,
                'points_rewards' => 150,
                'badge_type'     => 'silver',
                'badge_icon'     => 'achievements/savior.png',
                'display_order'  => 3,
            ],
            [
                'name'           => ['en' => 'Global Savior',       'ar' => 'المنقذ العالمي'],
                'description'    => ['en' => 'Donate blood 10 times.', 'ar' => 'تبرعت بالدم 10 مرات.'],
                'criteria_type'  => 'donations',
                'criteria_value' => 10,
                'points_rewards' => 300,
                'badge_type'     => 'gold',
                'badge_icon'     => 'achievements/global-savior.png',
                'display_order'  => 4,
            ],
            [
                'name'           => ['en' => 'Precious Treasure',   'ar' => 'الكنز الثمين'],
                'description'    => ['en' => 'Donate blood 25 times.', 'ar' => 'تبرعت بالدم 25 مرة.'],
                'criteria_type'  => 'donations',
                'criteria_value' => 25,
                'points_rewards' => 750,
                'badge_type'     => 'platinum',
                'badge_icon'     => 'achievements/precious-treasure.png',
                'display_order'  => 5,
            ],
            [
                'name'           => ['en' => 'The Golden Hundred',  'ar' => 'المائة الذهبية'],
                'description'    => ['en' => 'Donate blood 100 times.', 'ar' => 'تبرعت بالدم 100 مرة.'],
                'criteria_type'  => 'donations',
                'criteria_value' => 100,
                'points_rewards' => 2000,
                'badge_type'     => 'diamond',
                'badge_icon'     => 'achievements/golden-hundred.png',
                'display_order'  => 6,
            ],
            [
                'name'           => ['en' => 'The Legend',          'ar' => 'الأسطورة'],
                'description'    => ['en' => 'Reach 1000 points.', 'ar' => 'اجمع 1000 نقطة.'],
                'criteria_type'  => 'points',
                'criteria_value' => 1000,
                'points_rewards' => 0,
                'badge_type'     => 'diamond',
                'badge_icon'     => 'achievements/legend.png',
                'display_order'  => 7,
            ],
            [
                'name'           => ['en' => 'Emergency Hero',      'ar' => 'بطل الطوارئ'],
                'description'    => ['en' => 'Donate in response to a critical blood request.', 'ar' => 'تبرعت استجابةً لطلب دم حرج.'],
                'criteria_type'  => 'critical_donations',
                'criteria_value' => 1,
                'points_rewards' => 100,
                'badge_type'     => 'gold',
                'badge_icon'     => 'achievements/emergency-hero.png',
                'display_order'  => 8,
            ],
            [
                'name'           => ['en' => 'Rare Blood Type',     'ar' => 'الفصيلة النادرة'],
                'description'    => ['en' => 'You have a rare blood type. Your donation is especially precious.', 'ar' => 'لديك فصيلة دم نادرة. تبرعك نادر وثمين.'],
                'criteria_type'  => 'rare_blood_type',
                'criteria_value' => 1,
                'points_rewards' => 200,
                'badge_type'     => 'gold',
                'badge_icon'     => 'achievements/rare-blood-type.png',
                'display_order'  => 9,
            ],
            
            // Phase 2
            [
                'name'           => ['en' => 'Regular Month', 'ar' => 'الشهر المنتظم'],
                'description'    => ['en' => 'Donate in one calendar month.', 'ar' => 'تبرعت في شهر تقويمي واحد.'],
                'criteria_type'  => 'active_months',
                'criteria_value' => 1,
                'points_rewards' => 50,
                'badge_type'     => 'bronze',
                'badge_icon'     => 'achievements/regular-month.png',
                'display_order'  => 10,
            ],
            [
                'name'           => ['en' => 'Quarter-Year Committed', 'ar' => 'ربع السنة الملتزم'],
                'description'    => ['en' => 'Donate in 3 distinct calendar months.', 'ar' => 'تبرعت في 3 أشهر تقويمية مختلفة.'],
                'criteria_type'  => 'active_months',
                'criteria_value' => 3,
                'points_rewards' => 100,
                'badge_type'     => 'silver',
                'badge_icon'     => 'achievements/quarter-year-committed.png',
                'display_order'  => 11,
            ],
            [
                'name'           => ['en' => 'Steady Half-Year', 'ar' => 'نصف العام الثابت'],
                'description'    => ['en' => 'Donate in 6 distinct calendar months.', 'ar' => 'تبرعت في 6 أشهر تقويمية مختلفة.'],
                'criteria_type'  => 'active_months',
                'criteria_value' => 6,
                'points_rewards' => 200,
                'badge_type'     => 'gold',
                'badge_icon'     => 'achievements/steady-half-year.png',
                'display_order'  => 12,
            ],
            [
                'name'           => ['en' => 'A Year of Giving', 'ar' => 'عام من العطاء'],
                'description'    => ['en' => 'Donate in one calendar year.', 'ar' => 'تبرعت في عام تقويمي واحد.'],
                'criteria_type'  => 'active_years',
                'criteria_value' => 1,
                'points_rewards' => 400,
                'badge_type'     => 'gold',
                'badge_icon'     => 'achievements/year-of-giving.png',
                'display_order'  => 13,
            ],
            [
                'name'           => ['en' => 'Two Continuous Years', 'ar' => 'العامان المتواصلان'],
                'description'    => ['en' => 'Donate in 2 distinct calendar years.', 'ar' => 'تبرعت في عامين تقويميين مختلفين.'],
                'criteria_type'  => 'active_years',
                'criteria_value' => 2,
                'points_rewards' => 800,
                'badge_type'     => 'platinum',
                'badge_icon'     => 'achievements/two-continuous-years.png',
                'display_order'  => 14,
            ],
            [
                'name'           => ['en' => 'No Cancellation', 'ar' => 'لا إلغاء'],
                'description'    => ['en' => 'Complete 5 donations without any cancellations.', 'ar' => 'أكمل 5 تبرعات دون أي إلغاء.'],
                'criteria_type'  => 'streak_no_cancel',
                'criteria_value' => 5,
                'points_rewards' => 150,
                'badge_type'     => 'silver',
                'badge_icon'     => 'achievements/no-cancellation.png',
                'display_order'  => 15,
            ],
            [
                'name'           => ['en' => 'The Committed', 'ar' => 'الملتزم'],
                'description'    => ['en' => 'Complete 10 donations without any cancellations.', 'ar' => 'أكمل 10 تبرعات دون أي إلغاء.'],
                'criteria_type'  => 'streak_no_cancel',
                'criteria_value' => 10,
                'points_rewards' => 300,
                'badge_type'     => 'gold',
                'badge_icon'     => 'achievements/committed.png',
                'display_order'  => 16,
            ],
            [
                'name'           => ['en' => 'The Disciplined', 'ar' => 'المنضبط'],
                'description'    => ['en' => 'Have a 100% completion rate for 5 donations.', 'ar' => 'احصل على معدل إكمال 100٪ لـ 5 تبرعات.'],
                'criteria_type'  => 'completion_rate_100',
                'criteria_value' => 5,
                'points_rewards' => 200,
                'badge_type'     => 'gold',
                'badge_icon'     => 'achievements/disciplined.png',
                'display_order'  => 17,
            ],
            [
                'name'           => ['en' => 'The Reliable', 'ar' => 'الموثوق'],
                'description'    => ['en' => 'Have a 100% completion rate for 10 donations.', 'ar' => 'احصل على معدل إكمال 100٪ لـ 10 تبرعات.'],
                'criteria_type'  => 'completion_rate_100',
                'criteria_value' => 10,
                'points_rewards' => 400,
                'badge_type'     => 'platinum',
                'badge_icon'     => 'achievements/reliable.png',
                'display_order'  => 18,
            ],
            [
                'name'           => ['en' => 'Perfection', 'ar' => 'الكمالية'],
                'description'    => ['en' => 'Have a 100% completion rate for 25 donations.', 'ar' => 'احصل على معدل إكمال 100٪ لـ 25 تبرعًا.'],
                'criteria_type'  => 'completion_rate_100',
                'criteria_value' => 25,
                'points_rewards' => 750,
                'badge_type'     => 'diamond',
                'badge_icon'     => 'achievements/perfection.png',
                'display_order'  => 19,
            ],
            [
                'name'           => ['en' => 'Always Ready', 'ar' => 'دائما جاهز'],
                'description'    => ['en' => 'Complete 20 donations without any cancellations.', 'ar' => 'أكمل 20 تبرعًا دون أي إلغاء.'],
                'criteria_type'  => 'streak_no_cancel',
                'criteria_value' => 20,
                'points_rewards' => 500,
                'badge_type'     => 'platinum',
                'badge_icon'     => 'achievements/always-ready.png',
                'display_order'  => 20,
            ],
            // Phase 3
            [
                'name'           => ['en' => 'Quick Response', 'ar' => 'الاستجابة السريعة'],
                'description'    => ['en' => 'Respond to a request within 4 hours.', 'ar' => 'الاستجابة لطلب خلال 4 ساعات.'],
                'criteria_type'  => 'response_time_fast',
                'criteria_value' => 4,
                'points_rewards' => 75,
                'badge_type'     => 'bronze',
                'badge_icon'     => 'achievements/quick-response.png',
                'display_order'  => 21,
            ],
            [
                'name'           => ['en' => 'Immediate Reply', 'ar' => 'الرد الفوري'],
                'description'    => ['en' => 'Respond to a request within 2 hours.', 'ar' => 'الاستجابة لطلب خلال ساعتين.'],
                'criteria_type'  => 'response_time_fast',
                'criteria_value' => 2,
                'points_rewards' => 100,
                'badge_type'     => 'silver',
                'badge_icon'     => 'achievements/immediate-reply.png',
                'display_order'  => 22,
            ],
            [
                'name'           => ['en' => 'Lightning Bolt', 'ar' => 'صاعقة البرق'],
                'description'    => ['en' => 'Respond to a request within 1 hour.', 'ar' => 'الاستجابة لطلب خلال ساعة واحدة.'],
                'criteria_type'  => 'response_time_fast',
                'criteria_value' => 1,
                'points_rewards' => 150,
                'badge_type'     => 'gold',
                'badge_icon'     => 'achievements/lightning-bolt.png',
                'display_order'  => 23,
            ],
            [
                'name'           => ['en' => 'Local Hero', 'ar' => 'البطل المحلي'],
                'description'    => ['en' => 'Donate in 1 governorate.', 'ar' => 'تبرع في محافظة واحدة.'],
                'criteria_type'  => 'governorate_count',
                'criteria_value' => 1,
                'points_rewards' => 50,
                'badge_type'     => 'bronze',
                'badge_icon'     => 'achievements/local-hero.png',
                'display_order'  => 24,
            ],
            [
                'name'           => ['en' => 'Generous Neighbor', 'ar' => 'الجار الكريم'],
                'description'    => ['en' => 'Donate in 2 different governorates.', 'ar' => 'تبرع في محافظتين مختلفتين.'],
                'criteria_type'  => 'governorate_count',
                'criteria_value' => 2,
                'points_rewards' => 100,
                'badge_type'     => 'silver',
                'badge_icon'     => 'achievements/generous-neighbor.png',
                'display_order'  => 25,
            ],
            [
                'name'           => ['en' => 'The Traveler', 'ar' => 'المسافر'],
                'description'    => ['en' => 'Donate in 3 different governorates.', 'ar' => 'تبرع في 3 محافظات مختلفة.'],
                'criteria_type'  => 'governorate_count',
                'criteria_value' => 3,
                'points_rewards' => 150,
                'badge_type'     => 'gold',
                'badge_icon'     => 'achievements/traveler.png',
                'display_order'  => 26,
            ],
            [
                'name'           => ['en' => 'Long Traveler', 'ar' => 'المسافر الطويل'],
                'description'    => ['en' => 'Donate in 4 different governorates.', 'ar' => 'تبرع في 4 محافظات مختلفة.'],
                'criteria_type'  => 'governorate_count',
                'criteria_value' => 4,
                'points_rewards' => 200,
                'badge_type'     => 'platinum',
                'badge_icon'     => 'achievements/long-traveler.png',
                'display_order'  => 27,
            ],
            [
                'name'           => ['en' => 'Cross-Border', 'ar' => 'العابر للحدود'],
                'description'    => ['en' => 'Donate in 5 different governorates.', 'ar' => 'تبرع في 5 محافظات مختلفة.'],
                'criteria_type'  => 'governorate_count',
                'criteria_value' => 5,
                'points_rewards' => 250,
                'badge_type'     => 'diamond',
                'badge_icon'     => 'achievements/cross-border.png',
                'display_order'  => 28,
            ],
            [
                'name'           => ['en' => 'Sector Tour', 'ar' => 'جولة القطاع'],
                'description'    => ['en' => 'Donate in 5 different governorates.', 'ar' => 'تبرع في 5 محافظات مختلفة.'],
                'criteria_type'  => 'governorate_count',
                'criteria_value' => 5,
                'points_rewards' => 300,
                'badge_type'     => 'gold',
                'badge_icon'     => 'achievements/sector-tour.png',
                'display_order'  => 29,
            ],
            [
                'name'           => ['en' => 'Global Future', 'ar' => 'المستقبل العالمي'],
                'description'    => ['en' => 'Donate in 5 different governorates.', 'ar' => 'تبرع في 5 محافظات مختلفة.'],
                'criteria_type'  => 'governorate_count',
                'criteria_value' => 5,
                'points_rewards' => 500,
                'badge_type'     => 'diamond',
                'badge_icon'     => 'achievements/global-future.png',
                'display_order'  => 30,
            ],
            [
                'name'           => ['en' => 'Ramadan Hero', 'ar' => 'بطل رمضان'],
                'description'    => ['en' => 'Donate during Ramadan.', 'ar' => 'تبرع خلال شهر رمضان.'],
                'criteria_type'  => 'special_date',
                'criteria_value' => 1,
                'points_rewards' => 200,
                'badge_type'     => 'gold',
                'badge_icon'     => 'achievements/ramadan-hero.png',
                'display_order'  => 31,
            ],
            [
                'name'           => ['en' => 'World Donor Day', 'ar' => 'يوم المتبرع العالمي'],
                'description'    => ['en' => 'Donate on World Blood Donor Day.', 'ar' => 'تبرع في يوم المتبرع العالمي بالدم.'],
                'criteria_type'  => 'special_date',
                'criteria_value' => 2,
                'points_rewards' => 200,
                'badge_type'     => 'gold',
                'badge_icon'     => 'achievements/world-donor-day.png',
                'display_order'  => 32,
            ],
            [
                'name'           => ['en' => 'The Precise', 'ar' => 'الدقيق'],
                'description'    => ['en' => 'Respond to a request exactly on time.', 'ar' => 'الاستجابة لطلب في الوقت المحدد.'],
                'criteria_type'  => 'response_time_fast',
                'criteria_value' => 1,
                'points_rewards' => 100,
                'badge_type'     => 'silver',
                'badge_icon'     => 'achievements/the-precise.png',
                'display_order'  => 33,
            ],
        ];

        foreach ($achievements as $data) {
            Achievement::updateOrCreate(
                ['criteria_type' => $data['criteria_type'], 'criteria_value' => $data['criteria_value']],
                $data
            );
        }
    }
}
