<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Auth\RegisteredUserController;
use Mcamara\LaravelLocalization\Facades\LaravelLocalization;

use App\Http\Controllers\PublicPagesController;

// Email verification route must be outside the locale prefix group.
// The signed URL is generated by the queue worker (no HTTP context), which produces
// a URL without a locale prefix. Registering it here ensures the link works directly.
Route::get('verify-email/{id}/{hash}', \App\Http\Controllers\Auth\VerifyEmailController::class)
    ->middleware(['signed', 'throttle:6,1'])
    ->name('verification.verify');

Route::group([
    'prefix' => LaravelLocalization::setLocale(),
    'middleware' => ['localeSessionRedirect', 'localizationRedirect', 'localeViewPath']
], function () {
    // Public Pages
    Route::get('/', [PublicPagesController::class, 'home'])->name('home');
    Route::get('/about', [PublicPagesController::class, 'about'])->name('about');
    Route::get('/contact', [PublicPagesController::class, 'contact'])->name('contact');
    Route::post('/contact', [\App\Http\Controllers\ContactController::class, 'submit'])
        ->name('contact.submit')
        ->middleware('throttle:3,1');
    Route::get('/eligibility', [PublicPagesController::class, 'eligibility'])->name('eligibility');
    Route::get('/terms', [PublicPagesController::class, 'terms'])->name('terms');


    // Registration Pages
    Route::middleware('guest')->group(function () {
        Route::get('register_selection', [RegisteredUserController::class, 'showRegisterSelection'])
            ->name('register.selection');

        // Donor Registration
        Route::get('register/donor', [RegisteredUserController::class, 'showDonorRegistrationForm'])
            ->name('register.donor');
        Route::post('register/donor', [RegisteredUserController::class, 'storeDonor'])
            ->name('register.donor.store');

        // Organization Registration
        Route::get('register/organization', [RegisteredUserController::class, 'showOrganizationRegistrationForm'])
            ->name('register.organization');
        Route::post('register/organization', [RegisteredUserController::class, 'storeOrganization'])
            ->name('register.organization.store');
    });

    // Default Auth Routes
    require __DIR__ . '/auth.php';
});
