<?php

namespace App\Filament\Resources\Organizations\Schemas;

use Filament\Schemas\Schema;
use Filament\Schemas\Components\Section;

class OrganizationForm
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                Section::make()
                    ->columns(2)
                    ->schema([
                        TextInput::make('name')
                            ->required()
                            ->maxLength(255),
                        TextInput::make('email')
                            ->required()
                            ->maxLength(255),
                        TextInput::make('phone')
                            ->required()
                            ->maxLength(255),
                        TextInput::make('address')
                            ->required()
                            ->maxLength(255),
                        TextInput::make('city')
                            ->required()
                            ->maxLength(255),
                        TextInput::make('state')
                            ->required()
                            ->maxLength(255),
                        TextInput::make('zip')
                            ->required()
                            ->maxLength(255),
                        TextInput::make('country')
                            ->required()
                            ->maxLength(255),
                        TextInput::make('website')
                            ->required()
                            ->maxLength(255),
                        TextInput::make('logo')
                            ->required()
                            ->maxLength(255),
                        TextInput::make('favicon')
                            ->required()
                            ->maxLength(255),
                        TextInput::make('description')
                            ->required()
                            ->maxLength(255),
                        TextInput::make('keywords')
                            ->required()
                            ->maxLength(255),
                        TextInput::make('author')
                            ->required()
                            ->maxLength(255),
                        TextInput::make('copyright')
                            ->required()
                            ->maxLength(255),
                        TextInput::make('google_analytics')
                            ->required()
                            ->maxLength(255),
                        TextInput::make('google_tag_manager')
                            ->required()
                            ->maxLength(255),
                        TextInput::make('facebook')
                            ->required()
                            ->maxLength(255),
                        TextInput::make('twitter')
                            ->required()
                            ->maxLength(255),
                        TextInput::make('instagram')
                            ->required()
                            ->maxLength(255),
                        TextInput::make('linkedin')
                            ->required()
                            ->maxLength(255),
                        TextInput::make('youtube')
                            ->required()
                            ->maxLength(255),
                        TextInput::make('tiktok')
                            ->required()
                            ->maxLength(255),
                        TextInput::make('whatsapp')
                            ->required()
                            ->maxLength(255),
                        TextInput::make('telegram')
                            ->required()
                            ->maxLength(255),
                        TextInput::make('snapchat')
                            ->required()
                            ->maxLength(255),
                        TextInput::make('pinterest')
                            ->required()
                            ->maxLength(255),
                        TextInput::make('twitch')
                            ->required()
                            ->maxLength(255),
                        TextInput::make('tiktok')
                            ->required()
                            ->maxLength(255),
                        TextInput::make('tiktok')
                            ->required()
                            ->maxLength(255),
                        TextInput::make('tiktok')
                            ->required()
                            ->maxLength(255),
                        TextInput::make('tiktok')
                            ->required()
                            ->maxLength(255),
                        TextInput::make('tiktok')
                            ->required()
                            ->maxLength(255),
                        TextInput::make('tiktok')
                            ->required()
                            ->maxLength(255),
                        TextInput::make('tiktok')
                            ->required()
                            ->maxLength(255),
                        TextInput::make('tiktok')
                            ->required()
                            ->maxLength(255),
                        TextInput::make('tiktok')
                            ->required()
                            ->maxLength(255),
                        TextInput::make('tiktok')
                            ->required()
                            ->maxLength(255),
                        TextInput::make('tiktok')
                            ->required()
                            ->maxLength(255),
                        TextInput::make('tiktok')
                            ->required()
                            ->maxLength(255),
                        TextInput::make('tiktok')
                            ->required()
                            ->maxLength(255),
                        TextInput::make('tiktok')
                            ->required()
                            ->maxLength(255),
                        TextInput::make('tiktok')
                            ->required()
                            ->maxLength(255),
                        TextInput::make('tiktok')
                            ->required()
                            ->maxLength(255),
                        TextInput::make('tiktok')
                            ->required()
                            ->maxLength(255),
                        TextInput::make('tiktok')
                            ->required()
                            ->maxLength(255),
                        TextInput::make('tiktok')
                            ->required()
                            ->maxLength(255),
                        TextInput::make('tiktok')
                            ->required()
                            ->maxLength(255),
                        TextInput::make('tiktok')
                            ->required()
                            ->maxLength(255),
                        TextInput::make('tiktok')
                            ->required()
                            ->maxLength(255),
                        TextInput::make('tiktok')
                            ->required()
                            ->maxLength(255),
                        TextInput::make('tiktok')
                            ->required()
                            ->maxLength(255),
                        TextInput::make('tiktok')
                            ->required()
                            ->maxLength(255),
                        TextInput::make('tiktok')
                            ->required()
                            ->maxLength(255),
                        TextInput::make('tiktok')
                            ->required()
                            ->maxLength(255),
                        TextInput::make('tiktok')
                            ->required()
                            ->maxLength(255),
                        TextInput::make('tiktok')
                            ->required()
                            ->maxLength(255),
                        TextInput::make('tiktok')
                            ->required()
                            ->maxLength(255),
                        TextInput::make('tiktok')
                            ->required()
                            ->maxLength(255),
                        TextInput::make('tiktok')
                            ->required()
                            ->maxLength(255),
                        TextInput::make('tiktok')
                            ->required()
                            ->maxLength(255),
                        TextInput::make('tiktok')
                            ->required()
                            ->maxLength(255),
                        TextInput::make('tiktok')
                            ->required()
                            ->maxLength(255),
                        TextInput::make('tiktok')
                            ->required()
                            ->maxLength(255),
                        TextInput::make('tiktok')
                            ->required()
                            ->maxLength(255),
                        TextInput::make('tiktok')
                            ->required()
                            ->maxLength(255),
                        TextInput::make('tiktok')
                            ->required()
                            ->maxLength(255),
                        TextInput::make('tiktok')
